<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "message_type".
 *
 * @property integer $id
 * @property string $type
 *
 * @property \app\models\Message[] $messages
 * @property string $aliasModel
 */
abstract class MessageType extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'message_type';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['type'], 'string', 'max' => 100]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'type' => Yii::t('app', 'Type'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMessages()
    {
        return $this->hasMany(\app\models\Message::className(), ['id_message_type' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return MessageTypeQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\MessageTypeQuery(get_called_class());
    }


}
