<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "sender_type".
 *
 * @property integer $id
 * @property string $sender_type
 *
 * @property \app\models\Message[] $messages
 * @property string $aliasModel
 */
abstract class SenderType extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'sender_type';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['sender_type'], 'string', 'max' => 50]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'sender_type' => Yii::t('app', 'Sender Type'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMessages()
    {
        return $this->hasMany(\app\models\Message::className(), ['id_sender_type' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return SenderTypeQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\SenderTypeQuery(get_called_class());
    }


}
