<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "cases".
 *
 * @property integer $id
 * @property integer $id_contact
 * @property integer $id_category
 * @property integer $id_severity
 * @property integer $id_outcome
 * @property string $start_date
 * @property string $close_date
 * @property string $state
 * @property string $comments
 * @property string $aliasModel
 */
abstract class Cases extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'cases';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_contact', 'id_category', 'id_severity', 'id_outcome'], 'integer'],
            [['start_date', 'close_date'], 'safe'],
            [['comments'], 'string'],
            [['state'], 'string', 'max' => 50]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'id_contact' => Yii::t('app', 'Client'),
            'id_category' => Yii::t('app', 'Case Category'),
            'id_severity' => Yii::t('app', 'Severity'),
            'id_outcome' => Yii::t('app', 'Outcome'),
            'start_date' => Yii::t('app', 'Start Date'),
            'close_date' => Yii::t('app', 'Close Date'),
            'state' => Yii::t('app', 'State'),
            'comments' => Yii::t('app', 'Comments'),
        ];
    }



}
