<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "contact".
 *
 * @property integer $id
 * @property integer $id_country
 * @property integer $id_language
 * @property string $first_name
 * @property string $last_name
 * @property string $gender
 * @property string $marital_status
 * @property string $birthday
 * @property string $address_line1
 * @property string $address_line2
 * @property string $city
 * @property string $state
 * @property string $postal_code
 * @property string $comments
 * @property string $aliasModel
 */
abstract class Contact extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'contact';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['first_name'], 'required'],
            [['id_country', 'id_language'], 'integer'],
            [['birthday'], 'safe'],
            [['first_name', 'last_name', 'address_line1', 'address_line2', 'city', 'state'], 'string', 'max' => 50],
            [['gender', 'marital_status'], 'string', 'max' => 10],
            [['postal_code'], 'string', 'max' => 15],
            [['comments'], 'string', 'max' => 100]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'id_country' => Yii::t('app', 'Nationality'),
            'id_language' => Yii::t('app', 'First Language'),
            'first_name' => Yii::t('app', 'Names'),
            'last_name' => Yii::t('app', 'Surname'),
            'gender' => Yii::t('app', 'Gender'),
            'marital_status' => Yii::t('app', 'Marital Status'),
            'address_line1' => Yii::t('app', 'Address'),
            'address_line2' => Yii::t('app', 'Address'),
            'city' => Yii::t('app', 'City'),
            'state' => Yii::t('app', 'County'),
            'postal_code' => Yii::t('app', 'Postcode'),
            'comments' => Yii::t('app', 'Comments'),
        ];
    }





}
