<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "contact_phone".
 *
 * @property integer $id
 * @property integer $id_contact
 * @property string $id_phone
 *
 * @property \app\models\Contact $idContact
 * @property \app\models\Phone $idPhone
 * @property string $aliasModel
 */
abstract class ContactPhone extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'contact_phone';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_contact'], 'integer'],
            [['id_phone'], 'string', 'max' => 15],
            [['id_contact'], 'exist', 'skipOnError' => true, 'targetClass' => Contact::className(), 'targetAttribute' => ['id_contact' => 'id']],
            [['id_phone'], 'exist', 'skipOnError' => true, 'targetClass' => Phone::className(), 'targetAttribute' => ['id_phone' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'id_contact' => Yii::t('app', 'Contact'),
            'id_phone' => Yii::t('app', 'Phone'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdContact()
    {
        return $this->hasOne(\app\models\Contact::className(), ['id' => 'id_contact']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdPhone()
    {
        return $this->hasOne(\app\models\Phone::className(), ['id' => 'id_phone']);
    }


    
    /**
     * @inheritdoc
     * @return ContactPhoneQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\ContactPhoneQuery(get_called_class());
    }


}
