<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "languages".
 *
 * @property integer $id
 * @property string $language
 * @property string $short_name
 * @property string $aliasModel
 */
abstract class Languages extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'languages';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['language', 'short_name'], 'required'],
            [['language', 'short_name'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'language' => Yii::t('app', 'Language'),
            'short_name' => Yii::t('app', 'Short Name'),
        ];
    }



}
