<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "severity".
 *
 * @property integer $id
 * @property string $severity
 * @property string $sla
 * @property string $aliasModel
 */
abstract class Severity extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'severity';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['severity', 'sla'], 'required'],
            [['sla'], 'string'],
            [['severity'], 'string', 'max' => 50]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'severity' => Yii::t('app', 'Severity'),
            'sla' => Yii::t('app', 'Sla'),
        ];
    }


       

}
