<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\controllers\base;

use app\models\Profile;
use app\models\ProfileSearch;
use yii\web\Controller;
use yii\web\HttpException;
use yii\helpers\Url;
use yii\filters\AccessControl;
use yii\helpers\Json;

/**
* ProfileController implements the CRUD actions for Profile model.
*/
class ProfileController extends Controller
{
/**
* @var boolean whether to enable CSRF validation for the actions in this controller.
* CSRF validation is enabled only when both this property and [[Request::enableCsrfValidation]] are true.
*/
public $enableCsrfValidation = false;


/**
* Lists all Profile models.
* @return mixed
*/
//public function actionIndex()
//{
//    $searchModel  = new ProfileSearch;
//    $dataProvider = $searchModel->search($_GET);
//
//Tabs::clearLocalStorage();
//
//Url::remember();
//\Yii::$app->session['__crudReturnUrl'] = null;
//
//return $this->render('index', [
//'dataProvider' => $dataProvider,
//    'searchModel' => $searchModel,
//]);
//}



public function actionIndex()
{
    // your default model and dataProvider generated by gii
    $searchModel = new ProfileSearch;
    $dataProvider = $searchModel->search(\Yii::$app->request->getQueryParams());

    if (\Yii::$app->request->post('hasEditable')) {
        $profile_user_id = \Yii::$app->request->post('editableKey');
        $model = Profile::findOne($profile_user_id);
        $out = Json::encode(['output'=>'', 'message'=>'']);
        $posted = current($_POST['Profile']);
        $post = $posted['availability'];
        $model->availability =  $post;
        $model->save();
        $output = '';
        $out = Json::encode(['output'=>$output, 'message'=>'']);

        echo $out;
        return;
    }

    // non-ajax - render the grid by default
    return $this->render('index', [
        'dataProvider' => $dataProvider,
        'searchModel' => $searchModel
    ]);
}

/**
* Displays a single Profile model.
* @param integer $user_id
*
* @return mixed
*/
public function actionView($user_id)
{
\Yii::$app->session['__crudReturnUrl'] = Url::previous();
Url::remember();
Tabs::rememberActiveState();

return $this->render('view', [
'model' => $this->findModel($user_id),
]);
}

/**
* Creates a new Profile model.
* If creation is successful, the browser will be redirected to the 'view' page.
* @return mixed
*/
public function actionCreate()
{
$model = new Profile;

try {
if ($model->load($_POST) && $model->save()) {
return $this->redirect(['view', 'user_id' => $model->user_id]);
} elseif (!\Yii::$app->request->isPost) {
$model->load($_GET);
}
} catch (\Exception $e) {
$msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
$model->addError('_exception', $msg);
}
return $this->render('create', ['model' => $model]);
}

/**
* Updates an existing Profile model.
* If update is successful, the browser will be redirected to the 'view' page.
* @param integer $user_id
* @return mixed
*/
public function actionUpdate($user_id)
{
$model = $this->findModel($user_id);

if ($model->load($_POST) && $model->save()) {
return $this->redirect(Url::previous());
} else {
return $this->render('update', [
'model' => $model,
]);
}
}

/**
* Deletes an existing Profile model.
* If deletion is successful, the browser will be redirected to the 'index' page.
* @param integer $user_id
* @return mixed
*/
public function actionDelete($user_id)
{
try {
$this->findModel($user_id)->delete();
} catch (\Exception $e) {
$msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
\Yii::$app->getSession()->addFlash('error', $msg);
return $this->redirect(Url::previous());
}

// TODO: improve detection
$isPivot = strstr('$user_id',',');
if ($isPivot == true) {
return $this->redirect(Url::previous());
} elseif (isset(\Yii::$app->session['__crudReturnUrl']) && \Yii::$app->session['__crudReturnUrl'] != '/') {
Url::remember(null);
$url = \Yii::$app->session['__crudReturnUrl'];
\Yii::$app->session['__crudReturnUrl'] = null;

return $this->redirect($url);
} else {
return $this->redirect(['index']);
}
}

/**
* Finds the Profile model based on its primary key value.
* If the model is not found, a 404 HTTP exception will be thrown.
* @param integer $user_id
* @return Profile the loaded model
* @throws HttpException if the model cannot be found
*/
protected function findModel($user_id)
{
if (($model = Profile::findOne($user_id)) !== null) {
return $model;
} else {
throw new HttpException(404, 'The requested page does not exist.');
}
}
}
